# CI/CD Pipeline for Dashboard de Solicitação de Peças

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, staging ]
  pull_request:
    branches: [ main, develop, staging ]

# Global permissions - minimum required
permissions:
  contents: read

jobs:
  # Lint and code quality checks
  lint:
    name: Lint and Code Quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint:check
        continue-on-error: false

  # Unit tests
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Generate coverage report
        run: npm test -- --coverage
        continue-on-error: true
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true

  # Security checks
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true
      
      - name: Check for known vulnerabilities
        run: |
          echo "Checking for security vulnerabilities..."
          npm audit --json > audit-report.json || true
      
      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: security-audit
          path: audit-report.json

  # Build verification
  build:
    name: Build Verification
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify service worker
        run: |
          echo "Verifying service worker..."
          test -f service-worker.js
          echo "Service worker exists ✓"
      
      - name: Verify manifest
        run: |
          echo "Verifying manifest..."
          test -f manifest.webmanifest
          echo "Manifest exists ✓"
      
      - name: Check file structure
        run: |
          echo "Checking file structure..."
          test -d js
          test -d css
          test -d tests
          test -f index.html
          echo "File structure valid ✓"

  # Integration tests (placeholder for future e2e tests)
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run integration tests
        run: |
          echo "Integration tests placeholder"
          echo "TODO: Add Playwright or Cypress tests"
        continue-on-error: true

  # Deploy to staging (only on develop branch)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build, test, security]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    permissions:
      contents: read
    environment:
      name: staging
      url: https://staging.dashboard-pecas.example.com
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Actual deployment would use: ./scripts/deploy.sh staging
          # Requires Firebase token: firebase login:ci
          # Set token as GitHub secret: FIREBASE_TOKEN
          # Then use: firebase deploy --token "$FIREBASE_TOKEN" --only hosting:staging
          echo "See scripts/deploy.sh for deployment procedure"

  # Deploy to production (only on main branch)
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, test, security, integration]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write  # Needed for creating release
    environment:
      name: production
      url: https://dashboard-pecas.example.com
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create release tag
        run: |
          VERSION=$(date +'%Y.%m.%d')-${{ github.run_number }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Creating release tag v$VERSION"
      
      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Actual deployment would use: ./scripts/deploy.sh production
          # Requires Firebase token: firebase login:ci
          # Set token as GitHub secret: FIREBASE_TOKEN
          # Then use: firebase deploy --token "$FIREBASE_TOKEN" --only hosting
          echo "See scripts/deploy.sh for deployment procedure"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            Automated release from CI/CD pipeline
            
            Changes in this release:
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

  # Smoke tests after deployment
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: deploy-production
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run smoke tests
        run: |
          echo "Running smoke tests..."
          # Verify critical files exist
          test -f index.html
          test -f js/config.js
          test -f js/app.js
          test -f js/auth.js
          test -f js/logger.js
          test -f service-worker.js
          echo "Critical files exist ✓"
          
          # Verify production config defaults
          grep -q "environment: 'production'" js/config.js
          grep -q "showLoginCredentials: false" js/config.js
          echo "Production config defaults verified ✓"
          
          # Run unit tests as smoke check
          npm test
          echo "All tests passed ✓"

      - name: Check production availability
        run: |
          echo "Production availability check..."
          # TODO: Add actual production URL check when deployed
          # curl -f https://dashboard-pecas.example.com || exit 1
          echo "Smoke tests completed ✓"
